networks:
  wingtrip-network:
    driver: bridge

services:
  mysql-user:
    image: mysql:8.0
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: 'user_db'
      MYSQL_USER: ${USER_DB_USER}
      MYSQL_PASSWORD: ${USER_DB_PASS}
    ports:
      - '3310:3306'
    volumes:
      - mysql-user-data:/var/lib/mysql
      - ./api-user/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./api-user/src/main/resources/data.sql:/docker-entrypoint-initdb.d/2_data.sql
    env_file:
      - .env
    networks:
      - wingtrip-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  mysql-booking:
    image: mysql:8.0
    container_name: mysql-booking
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: 'booking_db'
      MYSQL_USER: ${BOOKING_DB_USER}
      MYSQL_PASSWORD: ${BOOKING_DB_PASS}
    ports:
      - '3311:3306'
    volumes:
      - mysql-booking-data:/var/lib/mysql
      - ./api-booking/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./api-booking/src/main/resources/data.sql:/docker-entrypoint-initdb.d/2_data.sql
    env_file:
      - .env
    networks:
      - wingtrip-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  mysql-payment:
    image: mysql:8.0
    container_name: mysql-payment
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: 'payment_db'
      MYSQL_USER: ${PAYMENT_DB_USER}
      MYSQL_PASSWORD: ${PAYMENT_DB_PASS}
    ports:
      - '3312:3306'
    volumes:
      - mysql-payment-data:/var/lib/mysql
      - ./api-payment/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./api-payment/src/main/resources/data.sql:/docker-entrypoint-initdb.d/2_data.sql
    env_file:
      - .env
    networks:
      - wingtrip-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  mongodb-flight:
    image: mongo:7.0
    container_name: mongodb-flight
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: 'flight_db'
    ports:
      - '27017:27017'
    volumes:
      - mongodb-flight-data:/data/db
      - mongodb-flight-config:/data/configdb
    env_file:
      - .env
    networks:
      - wingtrip-network
    healthcheck:
      test: [ "CMD", "mongosh", "--authenticationDatabase", "admin", "-u", "${MONGODB_USER}", "-p", "${MONGODB_PASSWORD}", "--eval", "db.adminCommand('ping')" ]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  config-server:
    build: ./config-server
    image: configserver:latest
    container_name: config-server
    ports:
      - "8888:8888"
    env_file:
      - .env
    networks:
      - wingtrip-network
    healthcheck:
        test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8888/actuator/health" ]
        timeout: 15s
        retries: 8
        interval: 15s
        start_period: 45s

  eureka-server:
    build: ./eureka-server
    image: eurekaserver:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    env_file:
      - .env
    networks:
      - wingtrip-network
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8761/actuator/health"]
      timeout: 15s
      retries: 8
      interval: 15s
      start_period: 60s

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - wingtrip-network
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9411/health" ]
      timeout: 10s
      retries: 3
      interval: 30s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" #Puerto AMQP
      - "15672:15672" #Puerto Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - wingtrip-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      timeout: 30s
      retries: 5
      interval: 30s
      start_period: 60s

  api-user:
    build: ./api-user
    container_name: api-user
    depends_on:
      mysql-user:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    ports:
      - "8081:8080"
    env_file:
      - .env
    networks:
      - wingtrip-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_HEALTHCHECK_ENABLED=true
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      timeout: 15s
      retries: 5
      interval: 30s
      start_period: 60s
    restart: on-failure

  api-booking:
    build: ./api-booking
    container_name: api-booking
    depends_on:
      mysql-booking:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8082:8080"
    env_file:
      - .env
    networks:
      - wingtrip-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_HEALTHCHECK_ENABLED=true
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health" ]
      timeout: 15s
      retries: 5
      interval: 30s
      start_period: 60s
    restart: on-failure

  api-payment:
    build: ./api-payment
    container_name: api-payment
    depends_on:
      mysql-payment:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8083:8080"
    env_file:
      - .env
    networks:
      - wingtrip-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_HEALTHCHECK_ENABLED=true
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health" ]
      timeout: 15s
      retries: 5
      interval: 30s
      start_period: 60s
    restart: on-failure

  api-flight:
    build: ./api-flight
    container_name: api-flight
    depends_on:
      mongodb-flight:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8084:8080"
    env_file:
      - .env
    networks:
      - wingtrip-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_HEALTHCHECK_ENABLED=true
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health" ]
      timeout: 15s
      retries: 5
      interval: 30s
      start_period: 60s
    restart: on-failure

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      api-user:
        condition: service_started
      api-flight:
        condition: service_started
    env_file:
      - .env
    networks:
      - wingtrip-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health" ]
      timeout: 15s
      retries: 8
      interval: 20s
      start_period: 90s
    restart: on-failure

volumes:
  mysql-user-data:
  mysql-booking-data:
  mysql-payment-data:
  mongodb-flight-data:
  mongodb-flight-config:
  rabbitmq-data:
