version: '3.8'

services:
  mysql-account:
    image: mysql:8.0
    container_name: mysql-account
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_DATABASE: 'account_db'
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - mysql-account-data:/var/lib/mysql
    env_file:
      - .env

  mysql-user:
    image: mysql:8.0
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: 'rootpassword'
      MYSQL_DATABASE: 'user_db'
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '3308:3306'
    expose:
      - '3308'
    volumes:
      - mysql-user-data:/var/lib/mysql
    env_file:
      - .env

  api-account:
    image: mysql:8.0
    environment:
      DATABASE_URL: jdbc:mysql://mysql-account:3306/account_db
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - mysql-account
    ports:
      - "8086:8086"

  api-user:
    image: mysql:8.0
    environment:
      DATABASE_URL: jdbc:mysql://mysql-user:3306/user_db
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - mysql-user
    ports:
      - "8087:8087"

volumes:
  mysql-account-data:
  mysql-user-data:
